{
 "title": "Parcheggi Bologna",
 "tags": [ "mobility" ],
 "time": { "from": "now/d-48h", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "parcking",
    "label": "Parcheggio",
    "query": "select parcheggio from parkings"
   }
  ]
 },
 "panels": [
  {
   "title": "Mappa parcheggi",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lat, lon, parcheggio, posti_totali FROM parkings LIMIT 50 "
    }
   ]
  },
  {
   "title": "Occupazione",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  hour, dow, AVG(posti_liberi) as posti FROM parking_data_aggregated where parcheggio = '$parcking'  GROUP BY hour, dow order by dow, hour"
    }
   ]
  },
  {
   "title": "Posti liberi",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(day, '5m'), posti_liberi as \"storico posti liberi\", parcheggio FROM parking_data_aggregated WHERE parcheggio = '$parcking' "
    }
   ]
  }
 ]
}