{
 "title": "Parcheggio-Bologna-d2",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "parcking",
    "label": "Parcheggio",
    "query": "select parcheggio from parkings"
   },
   {
    "name": "id",
    "label": "datasource Id",
    "query": "d3eb816d-a7fd-4a8d-bf5c-18530183fa4a"
   }
  ]
 },
 "panels": [
  {
   "title": "Mappa parcheggi",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT lat, lon, parcheggio, posti_totali FROM parkings LIMIT 50 "
    }
   ]
  },
  {
   "title": "Occupazione",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT  hour, dow, AVG(posti_liberi) as posti FROM parking_data_aggregated where parcheggio = '$parcking'  GROUP BY hour, dow order by dow, hour"
    }
   ]
  },
  {
   "title": "Posti liberi",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(day, '5m') AS time, posti_liberi as \"storico posti liberi\", parcheggio FROM parking_data_aggregated WHERE parcheggio = '$parcking' ORDER BY time ASC"
    },
    {
     "rawSql": "SELECT $__timeGroup(pp.datetime, '5m'), pp.parcheggio, p.posti_totali-pp.predicted_mean*p.posti_totali as \"previsione liberi sarimax\" FROM parkings_prediction pp inner join parkings p on pp.parcheggio = p.parcheggio WHERE pp.parcheggio = '$parcking' "
    },
    {
     "rawSql": "SELECT $__timeGroup(pp.datetime, '5m'), pp.parcheggio, p.posti_totali-pp.predicted_mean*p.posti_totali as \"previsione liberi Nbeats\" FROM parkings_prediction_nbeats pp inner join parkings p on pp.parcheggio = p.parcheggio WHERE pp.parcheggio = '$parcking' "
    },
    {
     "rawSql": "SELECT $__timeGroup(data, '20m'),posti_liberi as \"posti liberi attuali\",parcheggio FROM parkings_latest where parcheggio = '$parcking' \n"
    }
   ]
  }
 ]
}